version: '3.9'

services:
  management_node:
    image: mysql/mysql-cluster
    command: ndb_mgmd --ndb-nodeid=1
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./my.ini:/etc/my.cnf
      - ./config.ini:/etc/mysql-cluster.cnf
    ports:
      - "1186:1186"

  data_node_1:
    image: mysql/mysql-cluster
    command: ndbd
    depends_on:
      - management_node
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./my.ini:/etc/my.cnf
      - ./config.ini:/etc/mysql-cluster.cnf
      - data1:/usr/local/mysql/data

  data_node_2:
    image: mysql/mysql-cluster
    command: ndbd
    depends_on:
      - management_node
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./my.ini:/etc/my.cnf
      - ./config.ini:/etc/mysql-cluster.cnf
      - data2:/usr/local/mysql/data

  central_node:
    image: mysql/mysql-cluster
    command: mysqld
    depends_on:
      - data_node_1
      - data_node_2
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=all_movies
    volumes:
      - ./my.ini:/etc/my.cnf
      - ./config.ini:/etc/mysql-cluster.cnf
      - ./data:/usr/local/mysql/dump
    ports:
      - "3306:3306"

  node_2:
    image: mysql/mysql-cluster
    command: mysqld
    depends_on:
      - data_node_1
      - data_node_2
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=movies_before_1980
    volumes:
      - ./my.ini:/etc/my.cnf
      - ./config.ini:/etc/mysql-cluster.cnf
      - ./data:/usr/local/mysql/dump
    ports:
      - "3307:3306"

  node_3:
    image: mysql/mysql-cluster
    command: mysqld
    depends_on:
      - data_node_1
      - data_node_2
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=movies_from_1980
    volumes:
      - ./my.ini:/etc/my.cnf
      - ./config.ini:/etc/mysql-cluster.cnf
      - ./data:/usr/local/mysql/dump
    ports:
      - "3308:3306"
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: express-app
    ports:
      - '3000:3000'
    command: pnpm run dev
    volumes:
      - ./:/app

volumes:
  data1:
  data2:
